### PR TITLE
GetSpecificCategory

### PR DESCRIPTION
**Pull request by NNaik98**

### CODE REVIEW

**Comment by ppivanov** [comment]
You can add a test or 2 for this

**Comment by NNaik98** [comment]
adding test rn

**Comment by ppivanov** [comment]
> adding test rn 

Meant like a unit test or a system test with the inmemorydb unless you think it's not worth it

**Comment by ppivanov** [comment]
need the protected stuff gone to test some stuff. gonna fix stuff later

**Review by ppivanov — APPROVED** [review]

**Pull request merged**
